// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFdWBLYOoNlws0x2CmtH-pEktYrw8zGvc',
    appId: '1:949616045694:web:8e2135b1b02c3ab93ab22f',
    messagingSenderId: '949616045694',
    projectId: 'moodfit-71d4f',
    authDomain: 'moodfit-71d4f.firebaseapp.com',
    storageBucket: 'moodfit-71d4f.firebasestorage.app',
    measurementId: 'G-MQMG929XL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEADdhznIeIoXcMzBf8cAB9Axj_lccBsQ',
    appId: '1:949616045694:android:1bd5a5cbe198d37c3ab22f',
    messagingSenderId: '949616045694',
    projectId: 'moodfit-71d4f',
    storageBucket: 'moodfit-71d4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzTsJ3SDOm67PZRJwBE_ESBCec1EaMS2s',
    appId: '1:949616045694:ios:672273b6f6dddfc13ab22f',
    messagingSenderId: '949616045694',
    projectId: 'moodfit-71d4f',
    storageBucket: 'moodfit-71d4f.firebasestorage.app',
    iosClientId: '949616045694-1r6tbk7f9v3t0vl9p1m5ag1vdmfq6o2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodfit',
  );
}
